disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blueva Technologies"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_v0.png"

["params.author"]
image = "logo_profile.png"
